### ISSUE TITLE
Deleting a global alert gives error 500

### ISSUE THREAD

**Issue by fnurkla** [Dsek-LTH/web#193]
If you delete a global alert at the moment, you get served a 500 page. The alert is deleted as it should, but it still feels confusing for the user.

**Comment by danieladugyan** [comment]
Hm, I'm not quite sure to fix that (other than wrapping it in a try-catch but that's obviously not viable long-term). The reason it fails is because we have a access policy defined as `@@deny("read", removedAt != null)`. When an alert is deleted, we call `prisma.alert.update(...)``which attempts to return the updated alert after "deleting" it. But this is denied because the policy doesn't allow reading a deleted alert.

A possible fix would be to always allow users to read deleted entities if they have the permission to delete it.

**Comment by danieladugyan** [comment]
In fact, this should be a problem for all deletions, not just alerts.

**Comment by danieladugyan** [comment]
Apparently this is a known issue: https://github.com/zenstackhq/zenstack/issues/687. I'm guessing that indicates there is no elegant solution.
